services:
  service-user:
    container_name: ${SERVICE_USER_NAME}
    image: ${DOCKER_REPO}/${SERVICE_USER_NAME}:${SERVICE_USER_VERSION}
    ports:
      - "3001:3001"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/users"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  service-order:
    container_name: ${SERVICE_ORDER_NAME}
    image: ${DOCKER_REPO}/${SERVICE_ORDER_NAME}:${SERVICE_ORDER_VERSION}
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      service-user:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/orders"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  gateway:
    container_name: ${GATEWAY_NAME}
    image: ${DOCKER_REPO}/${GATEWAY_NAME}:${GATEWAY_VERSION}
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      service-user:
        condition: service_healthy
      service-order:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
